scope_request_task:
  agent: intake_coordinator
  description: "Analyze the research request for ticker '{ticker}' with timeframe '{timeframe}' and focus areas {focus_areas}. 
  Clarify the company name, exchange, and create a structured research brief with clear parameters and success criteria. 
  Use 'as of {current_date}' for all time-sensitive statements."
  expected_output: "A scoped brief including: company name/ticker, exchange, timeframe, focus areas, output format, constraints;
  include 3–5 peer candidates by SIC if available. Include an 'as_of' field set to '{current_date}'."

edgar_basics_task:
  agent: research_analyst
  description: "Research company with ticker '{ticker}'. First use sec_get_cik tool to resolve ticker→CIK, then use sec_recent_filings 
  tool to pull the 5–10 most recent relevant filings (10-K/10-Q/8-K), and capture links and notable Items from SEC. 
  Where possible, identify the current CEO from authoritative sources (e.g., latest DEF 14A, 10-K, leadership-change 8-K, or the company IR page) as of '{current_date}'."
  expected_output: "CIK, company name, SIC, CEO (as of {current_date}) and ceo_source_url; a list of recent filings with form type, filing date, accession, 
  Items summary (if 8-K), and direct document links. If uncertain on CEO, set 'ceo' to 'Unknown' and note why. Include 'as_of: {current_date}'."
  context:
    - scope_request_task

company_facts_snapshot_task:
  agent: financial_analyst
  description: "Using the CIK obtained from previous task for ticker '{ticker}', use sec_company_facts tool to fetch 
  core XBRL facts (revenue, operating income, net income, diluted EPS, shares, cash/FCF proxy, debt) and summarize {timeframe} 
  and simple trend vs. prior periods. Ensure all commentary is 'as of {current_date}'. 
  IMPORTANT: When calling sec_company_facts, pass only a key-value dict with the 10-digit zero-padded CIK from edgar_basics_task, exactly: {\"cik10\": \"<CIK10>\"}. 
  Do NOT include any other fields, example facts, or nested JSON in the tool input. 
  Also include the complete returned SEC company facts JSON in the task output under 'raw_facts'."
  expected_output: "A compact table of key metrics (LTM and last 2–3 periods), units/currency, and 3–5 bullet trend 
  notes with caveats (e.g., missing values, unit differences). Include an 'as_of' note set to {current_date}. Also include 'raw_facts' with the full SEC JSON."
  context:
    - edgar_basics_task

news_and_catalysts_task:
  agent: research_analyst
  description: "Use gdelt_news tool to search for recent news about ticker '{ticker}' for the past 14–30 days up to '{current_date}'; 
  deduplicate headlines; flag potential catalysts and risks based on focus areas {focus_areas}."
  expected_output: "A list of 5–10 recent items: date, source, title, link, and 1‑sentence relevance; top 3 catalysts/risks bullets. 
  Ensure item dates do not exceed {current_date}; include 'as_of: {current_date}'."
  context:
    - scope_request_task

price_context_task:
  agent: financial_analyst
  description: "Use stooq_prices tool to pull last 6–12 months of daily closes for ticker '{ticker}'; compute simple stats (1M/3M/6M/12M total return, volatility proxy) 
  and note any moves around recent filings from edgar_basics_task. Use '{current_date}' as the as-of date for all calculations."
  expected_output: "A small table of returns over common windows, a brief note on notable swings around filing dates, and any data caveats. Include 'as_of: {current_date}'."
  context:
    - scope_request_task
    - edgar_basics_task

synthesis_brief_task:
  agent: lead_synthesizer
  description: "Create a comprehensive research brief for ticker '{ticker}' (timeframe: '{timeframe}') by synthesizing all previous task outputs
   into a client-ready executive summary focusing on {focus_areas}. All facts and figures should be clearly stated as 'as of {current_date}'."
  expected_output: "One‑page summary: TL;DR (3 bullets), positives (3–5), risks (3–5), notable filings and dates, fundamentals takeaways (2–3), 
  recent catalysts (2–3), suggested next steps; include 'Not investment advice' disclaimer and an 'as_of' line with {current_date}."
  context:
    - company_facts_snapshot_task
    - news_and_catalysts_task
    - price_context_task