meta:
  version: 1
  schema_version: 1.0
  project: FinanceBuddy
  last_updated: 2025-08-20

scope_request_task:
  agent: intake_coordinator
  description: >
    Analyze the research request for ticker '{ticker}', timeframe '{timeframe}', and focus areas {focus_areas}.
    Create a structured research brief that will serve as the master instructions for all other analysts.
  output_file: "output/research_scope.json"
  expected_output: >
    Structured brief including: company name, ticker, timeframe, and focus_areas.
  context: []

edgar_basics_task:
  agent: edgar_research_analyst
  description: >
    Following the master instructions, conduct research on the company with ticker '{ticker}'.
    First, use get_sec_info to resolve the ticker to its CIK. Then, use get_recent_filings
    to get a list of all filings in the last 12 months (10-K, 10-Q, 8-K).
  output_file: "output/edgar_basics.json"
  expected_output: >
    A JSON object containing the CIK, company name, and a list of recent filings.
  context:
    - scope_request_task

company_facts_snapshot_task:
  agent: facts_reporter
  description: >
    Following the master instructions, your job is to get a summary of the company's financial facts.
    Use the 'get_company_facts' tool, passing the CIK provided by the edgar_basics_task.
    Your only task is to execute the tool and present the summarized data it returns. Do not add any analysis.
  output_file: "output/company_facts_snapshot.json"
  expected_output: >
    A JSON object containing a clean, structured table of the key financial metrics provided by the tool.
  context:
    - scope_request_task
    - edgar_basics_task

price_context_task:
  agent: price_reporter
  description: >
    Report the exact, pre-calculated return percentages provided to you. Do not perform calculations.
    - 1-Month Return: {d1m_return}%
    - 3-Month Return: {d3m_return}%
    - 6-Month Return: {d6m_return}%
    - 12-Month Return: {d12m_return}%
  output_file: "output/price_context.json"
  expected_output: >
    A structured JSON with the key-value pairs for the return percentages provided.
  context:
    - scope_request_task
    - edgar_basics_task

news_and_catalysts_task:
  agent: news_research_analyst
  description: >
    Following the master instructions, use the get_news tool to find recent news about '{ticker}' for the past 30 days.
    Your output should be a clean, summarized list of the top 5-10 most relevant articles.
  output_file: "output/news_and_catalysts.json"
  expected_output: >
    A clean list of 5–10 recent news items with date, source, title, and link.
  context:
    - scope_request_task

fundamental_analysis_task:
  agent: fundamental_analyst
  description: >
    Analyze the company's financial health based on the data reports.
    Review the financial facts and price context reports to provide 3-5 bullet points on fundamental strengths and weaknesses, 
    aligning with the original {focus_areas}.
  output_file: "output/fundamental_analysis.json"
  expected_output: >
    A JSON object with a 'fundamental_takeaways' key containing your analysis.
  context:
    - scope_request_task
    - company_facts_snapshot_task
    - price_context_task

qualitative_analysis_task:
  agent: qualitative_analyst
  description: >
    Analyze the company's strategic position based on the provided documents.
    Review the recent filings and news reports to provide 3-5 bullet points on qualitative strengths 
    and risks (brand, competition, management), aligning with the original {focus_areas}.
  output_file: "output/qualitative_analysis.json"
  expected_output: >
    A JSON object with a 'qualitative_takeaways' key containing your analysis.
  context:
    - scope_request_task
    - edgar_basics_task
    - news_and_catalysts_task

synthesis_brief_task:
  agent: lead_synthesizer
  description: >
    Synthesize all prior data and analysis reports into a single, client-ready executive brief for ticker '{ticker}'.
    Ensure the final report addresses the original {focus_areas} from the master instructions.
  output_file: "output/synthesis_brief.json"
  expected_output: >
    A comprehensive, one-page summary combining all data and analysis into a coherent brief.
  context:
    - scope_request_task
    - fundamental_analysis_task
    - qualitative_analysis_task
