# tasks.yaml
meta:
  version: 1
  schema_version: 1.0
  project: FinanceBuddy
  last_updated: 2025-08-17

scope_request_task:
  agent: intake_coordinator
  description: >
    Analyze the research request for ticker '{ticker}' with timeframe '{timeframe}' and focus areas {focus_areas}.
    Clarify the company name, exchange, and create a structured research brief with clear parameters and success criteria.
    Use 'as_of {current_date}' for all time-sensitive statements.
  output_file: "output/research_scope.json"
  expected_output: >
    Structured brief including: company name, ticker, exchange (if known), timeframe, focus areas, output_format, constraints;
    include 3–5 peer candidates by SIC if available. Include 'as_of' field set to '{current_date}'.
  context: []

edgar_basics_task:
  agent: research_analyst
  description: >
    Research company with ticker '{ticker}'. First call get_sec_info to resolve ticker → CIK, then call get_recent_filings
    to pull the 5–10 most relevant filings (10-K/10-Q/8-K). Capture direct document links and notable Items (e.g., 8‑K items).
    Where possible, identify the current CEO from authoritative sources (DEF 14A, 10‑K, 8‑K) as of '{current_date}'.
  output_file: "output/edgar_basics.json"
  expected_output: >
    CIK, company name, SIC, CEO (as of {current_date}) and ceo_source_url; a list of recent filings with form type, filing date,
    accession, Items summary (if 8‑K), and direct document links. If uncertain on CEO, set 'ceo' to 'Unknown' and note why.
    Include 'as_of: {current_date}'.
  tool_calls:
    - tool: "get_sec_info"
      input: { ticker: "{ticker}" }
      input_contract: { ticker: {type: "string", pattern: "^[A-Za-z0-9\\.\\-]{1,6}$"} }
    - tool: "get_recent_filings"
      input: { cik10: "{cik10}" }
      input_contract: { cik10: {type: "string", pattern: "^\\d{10}$"} }
  context:
    - scope_request_task

company_facts_snapshot_task:
  agent: financial_analyst
  description: >
    Using the CIK from edgar_basics_task for ticker '{ticker}', call get_company_facts with only {"cik10":"<CIK10>"}.
    Fetch core XBRL facts (revenue, operating income, net income, diluted EPS, shares, cash/FCF proxy, debt)
    and summarize {timeframe} with trends versus prior periods. Include raw_facts in the output.
  output_file: "output/company_facts_snapshot.json"
  expected_output: >
    Compact table of key metrics (LTM and last 2–3 periods), units/currency, and 3–5 trend bullet notes with caveats.
    Include 'as_of: {current_date}' and include the full SEC JSON under 'raw_facts'.
  tool_calls:
    - tool: "get_company_facts"
      input: { cik10: "{cik10}" }
      input_contract: { cik10: {type: "string", pattern: "^\\d{10}$", required: true} }
  context:
    - edgar_basics_task

news_and_catalysts_task:
  agent: research_analyst
  description: >
    Use get_news to search for recent news about ticker '{ticker}' for the past 14–30 days up to '{current_date}'.
    Deduplicate headlines and flag potential catalysts/risks aligned to the focus_areas.
  output_file: "output/news_and_catalysts.json"
  expected_output: >
    A list of 5–10 recent items: date, source, title, link, and 1‑sentence relevance; top 3 catalysts/risks bullets.
    Ensure item dates do not exceed {current_date}; include 'as_of: {current_date}'.
  tool_calls:
    - tool: "get_news"
      input: { query: "{ticker} OR {ticker}" }
      input_contract: { query: {type: "string"} }
  context:
    - scope_request_task

price_context_task:
  agent: financial_analyst
  description: >
    Use get_prices to pull the last 6–12 months of daily closes for ticker '{ticker}'; compute simple stats
    (1M/3M/6M/12M total return, volatility proxy) and note any moves around filing dates from edgar_basics_task.
  output_file: "output/price_context.json"
  expected_output: >
    A small table of returns over common windows, a brief note on notable swings around filing dates, and any data caveats.
    Include 'as_of: {current_date}'.
  tool_calls:
    - tool: "get_prices"
      input: { symbol: "{ticker}" }
      input_contract: { symbol: {type: "string"} }
  context:
    - scope_request_task
    - edgar_basics_task

synthesis_brief_task:
  agent: lead_synthesizer
  description: >
    Synthesize the prior task outputs into a client-ready executive brief for ticker '{ticker}' (timeframe: '{timeframe}').
    Focus on {focus_areas} and state all facts 'as of {current_date}'.
  output_file: "output/synthesis_brief.json"
  expected_output: >
    One-page summary: TL;DR (3 bullets), positives (3–5), risks (3–5), notable filings and dates, fundamentals takeaways (2–3),
    recent catalysts (2–3), suggested next steps; include 'Not investment advice' disclaimer and an 'as_of' line with {current_date}.
  context:
    - company_facts_snapshot_task
    - news_and_catalysts_task
    - price_context_task